### ISSUE TITLE
Include CHANGELOG.md file tracking changes

### ISSUE THREAD

**Issue by ofrei** [cmig-research-group/cmig_tools_deprecated#3]
I think cmig_tools would greatly benefit from having a CHANGELOG file.
A good idea would be to  follow best practices described here https://keepachangelog.com/en/1.0.0/

**Comment by pierre-nedelec** [comment]
The changelog is available in the [Release section](https://github.com/cmig-research-group/cmig_tools/releases). Its format is very close to the one described in keepachangelog link.
