### ISSUE TITLE
abcdConfig.m link is outdated

### ISSUE THREAD

**Issue by djhagler** [cmig-research-group/cmig_tools_deprecated#5]
Clicking on the abcdConfig.m link goes to a 404 - page not found message saying:
"The main branch of cmig_tools does not contain the path utils/matlab/abcdConfig.m."

It looks like like it was moved to cmig_tools_utils/matlab/abcdConfig.m.

**Comment by parekhpravesh** [comment]
Thanks for pointing out the broken links; we have fixed these in the internal version, which will be public soon.
